# fly.toml app configuration file generated for radio-proxy
app = "multi-radio-proxy"
primary_region = "scl"

[build]

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
